#! /bin/bash
# this will classify (align, identify) a read against the pathogen DB.

echo "[i]> === bwa"
date



inputfile="$1"
outputfile=$(basename $inputfile).bwa.sam
outdir="$2"

# this requires both the fasta and the reference generated by bwa to be in the same dir. TODO: check if links work.
referencefile=/rica_s/reference_genomes/joint/all_pathogens.fasta


/usr/bin/time -v bwa mem -t `nproc` -x ont2d $referencefile $inputfile > $outdir/$outputfile




date
echo "[i]> bwa ==="

