#! /bin/bash
# this will classify (align, identify) a read against the pathogen DB.

echo "[i]> === bwa"
date
echo ""


inputfile="$1"
outputfile=$(basename $inputfile)
outdir="$2"

# this requires both the fasta and the reference generated by bwa to be in the same dir. TODO: check if links work.
referencefile=/opt/rica_s/reference_genomes/joint/all_pathogens.fasta


/usr/bin/time -v bwa mem -t `nproc` -x ont2d $referencefile $inputfile > $outdir/$outputfile.bwa.sam
samtools view -F 2308 $outdir/$outputfile.bwa.sam | awk '{print $3}' | sort | uniq -c | awk -v OFS='\t' '{print $2, $1}' | sort -nr > $outdir/$outputfile.bwa.sam.tsv


echo ""
date
echo "[i]> bwa ==="

