services:
  rica_s_id_bwa:
    container_name: rica_s_id_bwa

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_bwa

    image: alkanlab/rica_s_id_bwa:v1.2

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    # build:
    #   context: .
    #   dockerfile_inline: |
    #     FROM alkanlab/rica_s_id_bwa:v1.1
    #     RUN apt update && apt install -y nano less git wget samtools seqtk seqkit