services:
  rica_s_id_kraken2:
    container_name: rica_s_id_kraken2

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_kraken2

    image: alkanlab/rica_s_id_kraken2:v1.1

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    build:
      context: .
      dockerfile_inline: |
        RUN apt update && apt install -y nano tail less git wget samtools seqtk seqkit
