services:
  rica_s_id_cuclark:
    container_name: rica_s_id_cuclark

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_cuclark

    image: alkanlab/rica_s_id_cuclark:v1.1

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# docker run --gpus all -it -v $(pwd):/data alkanlab/cuclark:latest