services:
  rica_s_id_clark:
    container_name: rica_s_id_clark

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_clark

    image: quay.io/biocontainers/clark:1.3.0.0--h9948957_0

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /home/ricardo/projects/rica_s:/rica_s
