services:
  rica_s_id_krakenuniq:
    container_name: rica_s_id_krakenuniq

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_krakenuniq

    image: alkanlab/rica_s_id_krakenuniq:v1.1

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s
