services:
  rica_s_id_bwa:
    container_name: rica_s_id_bwa

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_bwa

    image: staphb/bwa

    ipc: private

    logging:
      driver: json-file
      options: {}

    # mac_address: fe:da:fc:08:a3:3f

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /home/ricardo/projects/rica_s:/rica_s
