services:
  rica_s_id_clark:
    container_name: rica_s_id_clark

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_clark
    working_dir: /

    image: alkanlab/rica_s_id_clark:v1.5
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/CLARK/exe:/opt/CLARK/scripts

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    # build:
    #   context: .
    #   dockerfile_inline: |
    #     FROM alkanlab/rica_s_id_clark:v1.1 
    #     RUN apt update && apt install -y nano less git wget samtools seqtk seqkit
