services:
  rica_s_id_kraken2:
    container_name: rica_s_id_kraken2

    entrypoint:
      - /bin/bash

    hostname: rica_s_id_kraken2

    image: staphb/kraken2

    ipc: private

    logging:
      driver: json-file
      options: {}

    mac_address: a6:fb:54:78:61:77

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /home/ricardo/projects/rica_s:/rica_s
