services:
  rica_s_tl_tksm:
    container_name: rica_s_tl_pbsim3

    entrypoint:
      - /bin/bash
      
    hostname: rica_s_tl_pbsim3

    ipc: private

    image: alkanlab/pbsim3:v1.1

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    build:
      context: .
      dockerfile_inline: |
        RUN apt update && apt install -y nano tail less git wget samtools seqtk seqkit