services:
  rica_s_pr_card:
    container_name: rica_s_pr_card

    entrypoint:
      - /bin/bash

    hostname: rica_s_pr_card

    image: python:3.11-slim

    ipc: private

    logging:
      driver: json-file
      options: {}

    mac_address: 5e:31:3d:ea:cb:f1

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /home/ricardo/projects/rica_s:/rica_s
