services:
  rica_s_pr_abricate:
    container_name: rica_s_pr_abricate

    entrypoint:
      - /bin/bash

    hostname: rica_s_pr_abricate

    image: alkanlab/rica_s_pr_abricate:v1.3

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    # build:
    #   context: .
    #   dockerfile_inline: |
    #     FROM alkanlab/rica_s_pr_abricate:v1.2
    #     SHELL ["/bin/sh", "-c"]
        
        
    #     RUN apt update && apt install -y nano less git wget samtools seqtk seqkit curl bzip2 ca-certificates
        
        
    #     RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xj bin/micromamba && \
    #         mv bin/micromamba /usr/local/bin/micromamba && \
    #         rm -rf bin
            
        
    #     RUN micromamba create -y -p /opt/conda -c conda-forge -c bioconda abricate
        
        
    #     ENV PATH="/opt/conda/bin:$PATH"