services:
  rica_s_pr_abricate:
    container_name: rica_s_pr_abricate

    entrypoint:
      - /bin/bash

    hostname: rica_s_pr_abricate

    image: alkanlab/rica_s_pr_abricate:v1.2

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      - rica_s_net

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    build:
      context: .
      dockerfile_inline: |
        RUN apt update && apt install -y nano tail less git wget samtools seqtk seqkit curl
        "${SHELL}" <(curl -L micro.mamba.pm)
        source ~/.bashrc
        micromamba activate
        conda install -c conda-forge -c bioconda abricate

