services:
  rica_s_ui_web:
    container_name: rica_s_ui_web

    hostname: rica_s_ui_web

    image: ubuntu:stonking

    ipc: private

    logging:
      driver: json-file
      options: {}

    networks:
      rica_s_net:
        ipv4_address: 172.20.0.250 # Assign a static IP address within the subnet

    ports:
      - 5000:5000/tcp

    stdin_open: true

    tty: true

    volumes:
      - /opt/rica_s:/opt/rica_s

    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PYTHON_VERSION=3.14.0
      - PYTHON_SHA256=2299dae542d395ce3883aca00d3c910307cd68e0b2f7336098c8e7b7eee9f3e9

    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:stonking
        WORKDIR /opt/rica_s/tools/rica_s_ui_web
        COPY . .
        RUN apt update && apt install -y nano less git wget samtools seqtk seqkit python3 python3-pip
        RUN python3 -m pip install flask docker pyaml pandas --break-system-packages
        
